version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - CORS_ORIGINS=http://localhost:3000
    volumes:
      - ./backend/dataset:/app/dataset
      - ./backend/siamese_model.h5:/app/siamese_model.h5
    networks:
      - signet-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    networks:
      - signet-network

networks:
  signet-network:
    driver: bridge

volumes:
  model-data:
  dataset-data:
